AWSTemplateFormatVersion: "2010-09-09"
Description: Simple cloud formation for bucket creation and configuration

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: marios-espresso-pipeline-deployment-bucket
